<?php

/**
 * EventoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventoTable extends Doctrine_Table {
/**
 * Returns an instance of this class.
 *
 * @return object EventoTable
 */
    public static function getInstance() {
        return Doctrine_Core::getTable('Evento');
    }

    public function getEventosMes() {

        $fechaOrigen = date("y-m-d");
        list($año,$mes,$dia)=split("-", date("y-m-d"));
        $fechaOrigen = $año."-".$mes."-"."01";
        $fechaDestino = $año."-".$mes."-"."31";

        $eventosMes = Doctrine_Query::create()
            ->from('Evento e')
            ->where('e.fecha >= ?', $fechaOrigen)
            ->andWhere('e.fecha <= ?', $fechaDestino)
            ->fetchArray();
        return $eventosMes;
    }

    public function getEventosDia() {
        $eventosDia = Doctrine_Query::create()
            ->from('Evento e')
            ->where('e.fecha = ?', date('y-m-d'))
            ->fetchArray();

        return $eventosDia;
    }

    public function getEventosSemana() {

        $fechas = $this->obtenerSemana();
        $eventosDia = Doctrine_Query::create()
            ->from('Evento e')
            ->where('e.fecha >= ?', $fechas['origen'])
            ->andWhere('e.fecha <= ?', $fechas['destino'])
            ->fetchArray();

        return $eventosDia;
    }

    public function getEventosSiete() {

        $fechaOrigen = date("y-m-d");
        list($año,$mes,$dia)=split("-", date("y-m-d"));
        $fechaDestino = $nueva = mktime(0,0,0, $mes,$dia,$año) + 7 * 24 * 60 * 60;
        $fechaDestino=date("y-m-d",$fechaDestino);
        $eventosSiete = Doctrine_Query::create()
            ->from('Evento e')
            ->where('e.fecha >= ?', $fechaOrigen)
            ->andWhere('e.fecha <= ?', $fechaDestino)
            ->fetchArray();

        return $eventosSiete;
    }

    public function obtenerSemana() {


        $fechats = strtotime(date("y-m-d"));

        //el parametro w en la funcion date indica que queremos el dia de la semana
        //lo devuelve en numero 0 domingo, 1 lunes,....
        switch (date('w', $fechats)) {
            case 0:
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) - 6 * 24 * 60 * 60;
                $nuevaFecha=date("Y-m-d",$nueva);
                $fechas['origen'] = $nuevaFecha;
                $fechas['destino'] = date("y-m-d");
                return $fechas;
                break;
            case 1: echo "Lunes";
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) + 6 * 24 * 60 * 60;
                $nuevaFecha=date("Y-m-d",$nueva);
                $fechas['origen'] = date("y-m-d");
                $fechas¨['destino'] = $nuevaFecha;
                return $fechas;
                break;
            case 2: echo "Martes";
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) + 5 * 24 * 60 * 60;
                $fechaDestino=date("Y-m-d",$nueva);
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) - 1 * 24 * 60 * 60;
                $fechaOrigen=date("Y-m-d",$nueva);
                $fechas['origen'] = $fechaOrigen;
                $fechas¨['destino'] = $fechaDestino;
                return $fechas;
                break;
            case 3: echo "Miercoles";
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) + 4 * 24 * 60 * 60;
                $fechaDestino=date("Y-m-d",$nueva);
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) - 2 * 24 * 60 * 60;
                $fechaOrigen=date("Y-m-d",$nueva);
                $fechas['origen'] = $fechaOrigen;
                $fechas¨['destino'] = $fechaDestino;
                return $fechas;
                break;
            case 4: echo "Jueves";
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) + 3 * 24 * 60 * 60;
                $fechaDestino=date("Y-m-d",$nueva);
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) - 3 * 24 * 60 * 60;
                $fechaOrigen=date("Y-m-d",$nueva);
                $fechas['origen'] = $fechaOrigen;
                $fechas¨['destino'] = $fechaDestino;
                return $fechas;
                break;
            case 5: echo "Viernes";
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) + 2 * 24 * 60 * 60;
                $fechaDestino=date("Y-m-d",$nueva);
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) - 4 * 24 * 60 * 60;
                $fechaOrigen=date("Y-m-d",$nueva);
                $fechas['origen'] = $fechaOrigen;
                $fechas¨['destino'] = $fechaDestino;
                return $fechas;
                break;
            case 6: echo "Sabado";
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) + 1 * 24 * 60 * 60;
                $fechaDestino=date("Y-m-d",$nueva);
                list($año,$mes,$dia)=split("-", date("y-m-d"));
                $nueva = mktime(0,0,0, $mes,$dia,$año) - 5 * 24 * 60 * 60;
                $fechaOrigen=date("Y-m-d",$nueva);
                $fechas['origen'] = $fechaOrigen;
                $fechas¨['destino'] = $fechaDestino;
                return $fechas;
                break;
        }
    }


}